name: Run Crypto Signal Bot

on:
  workflow_dispatch:  # لتشغيله يدويًا
  schedule:
    - cron: '0 7 * * *'  # كل يوم الساعة 7 صباحًا UTC (10 صباحًا بتوقيت فلسطين)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python main.py
