name: Daily Crypto Signals Bot

on:
  schedule:
    - cron: '0 8 * * *'   # يومياً الساعة 8 صباحاً UTC (11 صباحاً بتوقيتك)
  workflow_dispatch:       # لتشغيل يدوي من GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
